export const AUTH = {
    ADMIN: "admin",
    DOCUMENT: {
        ACCESS_PRIVATE_DOCS: 'access-private-docs',
    },
    AUTHORIZATION: {
        CREATE: 'create-authorization',
        UPDATE: 'update-authorization',
        DELETE: 'delete-authorization',
        LIST:   'list-authorization',
        VIEW:   'view-authorization',
    },
    TASK: {
        CREATE: 'create-task',
        UPDATE: 'update-task',
        DELETE: 'delete-task',
        LIST:   'list-task',
        VIEW:   'view-task',
    },
    USER: {
        CHANGE_PASSWORD: 'change-password',
        CREATE: 'create-users',
        UPDATE: 'update-users',
        DELETE: 'delete-users',
        LIST:   'list-users',
        LOCK:   'lock-users',
        ASSIGN_GROUP:   'assign-group',
        REFRESH:   'refresh-users',
    },
    DEPARTMENT: {
        CREATE: 'create-department',
        UPDATE: 'update-department',
        DELETE: 'delete-department',
        LIST:   'list-department',
    },
    TICKET: {
        CREATE: 'create-ticket',
        UPDATE: 'update-ticket',
        DELETE: 'delete-ticket',
        LIST:   'list-ticket',
        CHANGE_LEVEL:   'change-level',
        VIEW:'view-ticket',
        HANDLE_ENTRY : 'department-handle-entry',
        HELP_DESK:'help-desk'
    },
    PRODUCT: {
        CREATE: 'create-product',
        UPDATE: 'update-product',
        DELETE: 'delete-product',
        LIST:   'list-product',
        LOCK:   'lock-product',
      },
    GROUP: {
        CREATE: 'create-group',
        UPDATE: 'update-group',
        DELETE: 'delete-group',
        LIST:   'list-group',
    },
    ROLE: {
        MANAGE: 'manage-roles',
        CREATE: 'create-roles',
        UPDATE: 'update-roles',
        DELETE: 'delete-roles',
        LIST:   'list-roles',
        LOCK:   'lock-roles',
    },
    CUSTOMER: {
        CREATE: 'create-customer',
        UPDATE: 'update-customer',
        DELETE: 'delete-customer',
        LIST:   'list-customer',
    },
    SLA: {
        CREATE: 'create-sla',
        UPDATE: 'update-sla',
        DELETE: 'delete-sla',
        LIST:   'list-sla',
        LOCK:   'lock-sla',
    },
    TICKET_CATEGORY_CONFIG: {
        CREATE: 'create-category-config',
        UPDATE: 'update-category-config',
        DELETE: 'delete-category-config',
        LIST:   'list-category-config',
        LOCK:   'lock-category-config',
    },
    TICKET_SOURCE_CONFIG: {
        CREATE: 'create-source-config',
        UPDATE: 'update-source-config',
        DELETE: 'delete-source-config',
        LIST:   'list-source-config',
        LOCK:   'lock-source-config'
    },
    TICKET_PRIORITY_CONFIG: {
        CREATE: 'create-priority-config',
        UPDATE: 'update-priority-config',
        DELETE: 'delete-priority-config',
        LIST:   'list-priority-config',
        LOCK:   'lock-priority-config',
    },
    TICKET_STATUS_CONFIG: {
        CREATE: 'create-status-config',
        UPDATE: 'update-status-config',
        DELETE: 'delete-status-config',
        LIST:   'list-status-config',
        LOCK:   'lock-status-config',
    },
    TRIGGER: {
        CREATE: 'create-trigger',
        UPDATE: 'update-trigger',
        DELETE: 'delete-trigger',
        LIST:   'list-trigger',
        LOCK:   'lock-trigger',
        VIEW:   'view-trigger',
    },
    CATEGORY: {
        CREATE: 'create-trigger',
        UPDATE: 'update-trigger',
        DELETE: 'delete-trigger',
        LIST:   'list-trigger',
        // VIEW:   'view-trigger',
    },
    SYSTEM_SOURCE_TICKET: {
        CREATE: 'create-source-ticket',
        UPDATE: 'update-source-ticket',
        DELETE: 'delete-source-ticket',
        LIST:   'list-source-ticket',
    },
    SYSTEM_WORKFLOW: {
        CREATE: 'create-workflow',
        UPDATE: 'update-workflow',
        DELETE: 'delete-workflow',
        LIST:   'list-workflow',
        INTERNALSLA: 'internal-sla'
    },
    SYSTEM_TEMPLATE: {
        CREATE: 'create-template',
        UPDATE: 'update-template',
        DELETE: 'delete-template',
        LIST:   'list-template',
    },
    REPORT: {
        TICKETS: 'ticket_execute_report',
        KPI: 'kpi_report',
        OUTDATE_TICKET: 'outdate_ticket_report',
        REQUEST_UPGRADE: 'request_upgrade',
    }
  };
